### ISSUE TITLE
Minecraft 1.17 support

### ISSUE THREAD

**Issue by GeorgH93** [GeorgH93/PCGF_PluginLib#20]
Minecraft 1.17 has been released. This plugin needs to be updated. This might take some time.

**TODO:**
- [x] NMS has been moved to different packages
  - [x] Update Reflection
  - [x] Update code generator
- [x] Fix Java 16 compatibility issues
- [x] Testing
